name: "deploy"
description: "Deploy repo"

runs:
  using: composite
  steps:
    - name: ssh
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}%
        script: |
          ls -al
          cd github/${{ github.event.repository.name }}
          ls -al
          cat ${{ github.event.repository.name }}
